version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use an image with Docker pre-installed
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7   # Ensures Docker runs properly in CircleCI
          docker_layer_caching: true  # Speeds up builds by caching layers
      - run:
          name: Verify Docker is Running
          command: docker info
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-app ./app
      - run:
          name: Display Message
          command: echo "Hello, World! - Docker image built successfully!"
