version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use CircleCI's Python image
    steps:
      - checkout
      
      - run:
          name: Build Docker Image
          command: docker build -t my-flask-app .
      - run:
          name: Run Docker Container
          command: docker run -d -p 5000:5000 my-flask-app

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
