version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # CircleCI’s Python image with Docker support
    steps:
      - checkout
      - setup_remote_docker  # Enables Docker inside CircleCI
      - run:
          name: List Files (Debug)
          command: ls -lah
      - run:
          name: Build Docker Image
          command: docker build -t my-flask-app .
      - run:
          name: Run Docker Container
          command: |
            docker run -d --name flask-container -p 5000:5000 my-flask-app
            sleep 5
            docker ps -a  # Debug: Check running containers
            docker logs flask-container  # Debug: Show container logs
            curl -f http://localhost:5000 || exit 1
      - run:
          name: Display Success Message
          command: echo "✅ Hello, World! - Docker container ran successfully!"

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
