version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # CircleCI’s Python image with Docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t my-flask-app .
      - run:
          name: Get Container IP and Test
          command: |
            CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' flask-container)
            echo "Flask is running on $CONTAINER_IP"
            curl -f http://$CONTAINER_IP:5000 || exit 1


workflows:
  version: 2
  build_and_run:
    jobs:
      - build
