version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
          access_remote_docker: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t flask-hello-world .

workflows:
  version: 2
  build:
    jobs:
      - build
