version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use CircleCI's Python image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14  # Ensure Docker daemon is properly set up
          docker_layer_caching: true  # Optional: Speeds up builds
      - run:
          name: Build Docker Image
          command: docker build -t my-flask-app .
      - run:
          name: Run Docker Container
          command: docker run -d -p 5000:5000 my-flask-app

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
