version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-app ./app
      - run:
          name: Run Docker Container
          command: docker run -d -p 5000:5000 hello-world-app
