version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # CircleCI’s optimized Python image
    steps:
      - checkout
      - setup_remote_docker  # Enables Docker in CircleCI
      - run:
          name: Debug Directory Structure
          command: ls -R  # Ensures app.py file is present
      - run:
          name: Build Docker Image
          command: docker build -t my-flask-app .
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 5000:5000 my-flask-app
            sleep 5
            curl -f http://localhost:5000 || exit 1
      - run:
          name: Display Success Message
          command: echo "✅ Hello, World! - Docker container ran successfully!"

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
