version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use CircleCI's optimized Python image
    steps:
      - checkout
      - setup_remote_docker  # Enables Docker in CircleCI
      - run:
          name: Build Docker image
          command: docker build -t my-flask-app .
      - run:
          name: Run Docker Container
          command: |
            docker run --rm my-flask-app
      - run:
          name: Display Success Message
          command: echo "✅ Hello, World! - Docker container ran successfully!"

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
